"use client";

import { FileJson, FileText } from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { formatDelta } from "@/lib/utils";
import type { ScenarioData } from "@/lib/api/types";

interface ScenarioReportPanelProps {
  data: ScenarioData;
}

function buildNarrative(data: ScenarioData): string {
  const impact = data.regime_impact ?? {};
  const baseline = (impact.baseline_regime as string)?.replace(/_/g, " ") ?? "the current regime";
  const simulated = (impact.simulated_regime as string)?.replace(/_/g, " ") ?? "the simulated regime";
  const magnitude = (impact.shift_magnitude as string) ?? "moderate";

  const sectors = data.sector_impacts ?? [];
  const sorted = [...sectors].sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta));
  const topPositive = sorted.find((s) => s.delta > 0);
  const topNegative = sorted.find((s) => s.delta < 0);

  const stocks = data.watchlist_impacts ?? [];
  const beneficiaryCount = stocks.filter((s) => s.delta > 0).length;
  const pressuredCount = stocks.filter((s) => s.delta < 0).length;
  const labelChanges = stocks.filter((s) => s.label_change).length;

  const uncertainties = data.uncertainty_notes ?? [];

  const lines: string[] = [];

  // Regime shift sentence
  if (baseline === simulated) {
    lines.push(
      `Under the "${data.description}" scenario, the regime classification remains at ${baseline}, suggesting the shock is largely absorbed within the current frame.`,
    );
  } else {
    lines.push(
      `The "${data.description}" scenario projects a ${magnitude} regime shift from ${baseline} to ${simulated}, indicating a meaningful change in the market environment.`,
    );
  }

  // Top sector impact
  if (topPositive && topNegative) {
    lines.push(
      `Among tracked sectors, ${topPositive.name} stands to benefit the most (${formatDelta(topPositive.delta)}), while ${topNegative.name} faces the greatest pressure (${formatDelta(topNegative.delta)}).`,
    );
  } else if (topPositive) {
    lines.push(
      `${topPositive.name} is the sector most likely to benefit under this scenario (${formatDelta(topPositive.delta)}).`,
    );
  } else if (topNegative) {
    lines.push(
      `${topNegative.name} faces the most significant pressure (${formatDelta(topNegative.delta)}).`,
    );
  }

  // Watchlist summary
  if (stocks.length > 0) {
    lines.push(
      `Across the watchlist, ${beneficiaryCount} name${beneficiaryCount !== 1 ? "s" : ""} see improved signals while ${pressuredCount} face deterioration.` +
        (labelChanges > 0
          ? ` Notably, ${labelChanges} name${labelChanges !== 1 ? "s" : ""} would see their signal label change.`
          : ""),
    );
  }

  // Uncertainty
  if (uncertainties.length > 0) {
    lines.push(
      `Key uncertainty factors include: ${uncertainties.slice(0, 2).join("; ")}. These should be monitored as the scenario unfolds.`,
    );
  }

  return lines.join(" ");
}

function buildMarkdownReport(data: ScenarioData, narrative: string): string {
  const impact = data.regime_impact ?? {};
  const lines: string[] = [
    `# Scenario Brief: ${data.scenario_name?.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) ?? "Unnamed"}`,
    "",
    `> ${data.description}`,
    "",
    "## Regime Impact",
    "",
    `- **Baseline**: ${(impact.baseline_regime as string) ?? "N/A"}`,
    `- **Simulated**: ${(impact.simulated_regime as string) ?? "N/A"}`,
    `- **Shift Magnitude**: ${(impact.shift_magnitude as string) ?? "N/A"}`,
    "",
    "## Narrative Summary",
    "",
    narrative,
    "",
  ];

  const sectors = data.sector_impacts ?? [];
  if (sectors.length > 0) {
    lines.push("## Sector Impacts", "", "| Sector | Baseline | Scenario | Delta |", "| --- | --- | --- | --- |");
    for (const s of sectors) {
      lines.push(
        `| ${s.name} | ${s.baseline_score.toFixed(1)} | ${s.scenario_score.toFixed(1)} | ${formatDelta(s.delta)} |`,
      );
    }
    lines.push("");
  }

  const stocks = data.watchlist_impacts ?? [];
  if (stocks.length > 0) {
    lines.push("## Watchlist Impacts", "", "| Symbol | Name | Delta | Label Change |", "| --- | --- | --- | --- |");
    for (const s of stocks) {
      lines.push(
        `| ${s.symbol} | ${s.name} | ${formatDelta(s.delta)} | ${s.label_change ?? "---"} |`,
      );
    }
    lines.push("");
  }

  const uncertainties = data.uncertainty_notes ?? [];
  if (uncertainties.length > 0) {
    lines.push("## Uncertainty Factors", "");
    for (const note of uncertainties) {
      lines.push(`- ${note}`);
    }
    lines.push("");
  }

  lines.push(
    "---",
    `*Generated by InvestorFrame Scenario Lab on ${new Date().toISOString().split("T")[0]}*`,
  );

  return lines.join("\n");
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ScenarioReportPanel({ data }: ScenarioReportPanelProps) {
  const narrative = buildNarrative(data);
  const scenarioSlug = data.scenario_name ?? "scenario";

  function handleExportJson() {
    downloadFile(
      JSON.stringify(data, null, 2),
      `${scenarioSlug}-report.json`,
      "application/json",
    );
  }

  function handleExportMarkdown() {
    const md = buildMarkdownReport(data, narrative);
    downloadFile(md, `${scenarioSlug}-report.md`, "text/markdown");
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Generated Scenario Brief</CardTitle>
        <CardDescription>
          A structured summary of how this scenario may reshape the market frame.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm leading-relaxed text-muted-foreground">
          {narrative}
        </p>

        <div className="flex items-center gap-2 pt-1">
          <Button variant="outline" size="sm" onClick={handleExportJson}>
            <FileJson className="mr-1.5 h-3.5 w-3.5" />
            Export JSON
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportMarkdown}>
            <FileText className="mr-1.5 h-3.5 w-3.5" />
            Export Markdown
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
